# Generated by Django 4.1.7 on 2023-02-24 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={"verbose_name_plural": "categories",},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tags_color",
                    models.CharField(
                        choices=[
                            ("S", "Shirt"),
                            ("Sp", "Sport wear"),
                            ("OW", "Out wear"),
                            ("PH", "Phone"),
                            ("SH", "Shoes"),
                        ],
                        default=("D", "danger"),
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Required",
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required",
                        max_digits=9,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                ("stocked", models.BooleanField(default=True, verbose_name="is_stock")),
                (
                    "digital",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="is_digital"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 24, 18, 8, 48, 83443, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="Updated at",
                    ),
                ),
                ("discount_price", models.FloatField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                        max_length=2,
                        null=True,
                        verbose_name="Labels",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="optional",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="Store.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                (
                    "main_pic",
                    models.BooleanField(default=False, verbose_name="main image"),
                ),
                ("other_pic1", models.BooleanField(default=False, verbose_name="Img2")),
                ("other_pic2", models.BooleanField(default=False, verbose_name="Img3")),
                ("other_pic3", models.BooleanField(default=False, verbose_name="Img4")),
                ("other_pic4", models.BooleanField(default=False, verbose_name="Img5")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 24, 18, 8, 48, 84442, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_image",
                        to="Store.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ("-updated",),
            },
        ),
    ]
