# Generated by Django 4.1.7 on 2023-04-05 05:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={"verbose_name_plural": "categories",},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        choices=[
                            ("S", "Shirt"),
                            ("Sp", "Sport wear"),
                            ("OW", "Out wear"),
                            ("PH", "Phone"),
                            ("SH", "Shoes"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Required",
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required",
                        max_digits=9,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                ("stocked", models.BooleanField(default=True, verbose_name="is_stock")),
                (
                    "digital",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="is_digital"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 37, 7, 371144, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Updated at",
                    ),
                ),
                ("discount_price", models.FloatField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                        default=("D", "danger"),
                        max_length=2,
                        null=True,
                        verbose_name="Label color",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="optional",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="optional",
                        null=True,
                        verbose_name="Additional Information",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="Store.category",
                    ),
                ),
                (
                    "users_wishlist",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item_Image4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=False, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 37, 7, 379123, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image4",
                        to="Store.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fourth Image",
                "verbose_name_plural": "Fourth Image",
            },
        ),
        migrations.CreateModel(
            name="Item_Image3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=False, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 37, 7, 379123, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image3",
                        to="Store.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third Image",
                "verbose_name_plural": "Third Image",
            },
        ),
        migrations.CreateModel(
            name="Item_Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=False, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 37, 7, 371144, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image2",
                        to="Store.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Second Image",
                "verbose_name_plural": "Second Image",
            },
        ),
        migrations.CreateModel(
            name="Item_Image1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=True, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 37, 7, 371144, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image1",
                        to="Store.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "First Image",
                "verbose_name_plural": "First Image",
            },
        ),
    ]
