# Generated by Django 4.1.7 on 2023-04-05 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0003_alter_item_updated_alter_item_image1_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="additional_info",
            field=models.TextField(
                blank=True,
                help_text="optional(applicable when adding Second-Fourth Images)",
                null=True,
                verbose_name="Additional Information",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="optional(briefly say about the product)",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 34, 584487, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="item_image1",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 34, 584487, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="item_image2",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 34, 584487, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="item_image3",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 34, 592485, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="item_image4",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 34, 592485, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="created at",
            ),
        ),
    ]
