# Generated by Django 4.1.7 on 2023-02-24 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0003_alter_item_updated_alter_item_image_updated"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="tags_color",),
        migrations.AddField(
            model_name="item",
            name="sub_category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("Sp", "Sport wear"),
                    ("OW", "Out wear"),
                    ("PH", "Phone"),
                    ("SH", "Shoes"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                default=("D", "danger"),
                max_length=2,
                null=True,
                verbose_name="Labels",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 24, 22, 24, 4, 467856, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="item_image",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 24, 22, 24, 4, 467856, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="created at",
            ),
        ),
    ]
