# Generated by Django 4.1.7 on 2023-02-25 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0004_remove_item_tags_color_item_sub_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item_Image1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=True, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 25, 7, 59, 6, 838952, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "First Image",
                "verbose_name_plural": "First Image",
            },
        ),
        migrations.CreateModel(
            name="Item_Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=False, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 25, 7, 59, 6, 838952, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Second Image",
                "verbose_name_plural": "Second Image",
            },
        ),
        migrations.CreateModel(
            name="Item_Image3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=False, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 25, 7, 59, 6, 838952, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third Image",
                "verbose_name_plural": "Third Image",
            },
        ),
        migrations.CreateModel(
            name="Item_Image4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload Item's image",
                        null=True,
                        upload_to="products/%y/%m",
                        verbose_name="Image",
                    ),
                ),
                ("Show", models.BooleanField(default=False, verbose_name="show")),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 25, 7, 59, 6, 838952, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fourth Image",
                "verbose_name_plural": "Fourth Image",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 25, 7, 59, 6, 838952, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Updated at",
            ),
        ),
        migrations.DeleteModel(name="Item_Image",),
        migrations.AddField(
            model_name="item_image4",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image4",
                to="Store.item",
            ),
        ),
        migrations.AddField(
            model_name="item_image3",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image3",
                to="Store.item",
            ),
        ),
        migrations.AddField(
            model_name="item_image2",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image2",
                to="Store.item",
            ),
        ),
        migrations.AddField(
            model_name="item_image1",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image1",
                to="Store.item",
            ),
        ),
    ]
