# Generated by Django 4.1.7 on 2023-04-05 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 8, 37, 35, 383911, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 8, 37, 35, 383911, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Updated at",
            ),
        ),
    ]
