# Generated by Django 4.1.7 on 2023-02-28 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0006_alter_address_created_at_alter_address_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="name", new_name="full_name",
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 7, 22, 44, 334140, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 7, 22, 44, 334140, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(
                blank=True, help_text="Optional ", max_length=50, verbose_name="zipcode"
            ),
        ),
    ]
