# Generated by Django 4.1.7 on 2023-02-28 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0008_alter_address_created_at_alter_address_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="full_name", new_name="name",
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 7, 33, 51, 311809, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 7, 33, 51, 311809, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Updated at",
            ),
        ),
    ]
