# Generated by Django 4.1.7 on 2023-04-05 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Required ",
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        help_text="Required",
                        max_length=200,
                        unique=True,
                        verbose_name="user name",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Required ",
                        max_length=200,
                        null=True,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Required ",
                        max_length=200,
                        null=True,
                        verbose_name="last name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Required ",
                        max_length=200,
                        null=True,
                        verbose_name="phone",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 34, 52, 146112, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 5, 8, 34, 52, 146112, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
            },
        ),
    ]
