# Generated by Django 4.1.7 on 2023-04-05 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 8, 38, 1, 116976, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 8, 38, 1, 116976, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
