# Generated by Django 4.1.7 on 2023-04-05 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_account_created_alter_account_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 53, 40, 498739, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 53, 40, 498739, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
