# Generated by Django 4.1.7 on 2023-02-28 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_alter_account_created_alter_account_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="las_name", new_name="last_name",
        ),
        migrations.AlterField(
            model_name="account",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 7, 30, 21, 147001, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 7, 30, 21, 147001, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
