# Generated by Django 4.1.7 on 2023-04-05 07:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0005_alter_address_created_at_alter_address_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Order", "0002_alter_order_date_ordered_alter_orderitem_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="customer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 55, 599607, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False, verbose_name="Order completed"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 55, 599607, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="ordered",
            field=models.BooleanField(default=False, verbose_name="Order completed"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 55, 599607, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refund_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 5, 10, 54, 55, 599607, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
