# Generated by Django 4.1.7 on 2023-04-06 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0005_userprofile_user_alter_order_date_ordered_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="customer",),
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 6, 16, 18, 46, 993567, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 6, 16, 18, 46, 993567, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 6, 16, 18, 46, 993567, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refund_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 6, 16, 18, 46, 993567, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
